### ISSUE TITLE
Incorrect font is showing in the menu

### ISSUE THREAD

**Issue by Spajki001** [AdisonCavani/distro-grub-themes#101]
**Describe the bug**
After I successfully set the grub theme I wanted (in my case the Acer theme), it showed up fine but the text for the names of grub entries and the countdown text above is not shown in a pretty font as is seen on creator's screenshots but instead it shows me an ugly terminal font.

**Expected behavior**
I expected that the pretty font would be shown but it isn't.

**Screenshots**
![20230131_125346](https://user-images.githubusercontent.com/101796404/215753573-ea65c5f0-f9b7-41f7-8865-eadcc3668599.jpg)

**Desktop**
 - OS: Ubuntu 22.10 in dual boot with Windows 11
 - Resolution 1920x1080

**Comment by AdisonCavani** [comment]
From which source did you downloaded theme archive?
- Github - master branch
- Github - release
- Pling/gnome-look ect.

**Comment by nicholasz2510** [comment]
I've had this issue too with different grub themes; it's caused by a change to how fonts are loaded in grub when secure boot is enabled. To remove some secure boot holes, they made it so only signed fonts are available. Looks like currently the only available font is the GNU Unifont. 

Right now, the main fixes are to either disable secure boot (unfortunately) or patch grub locally to remove the changes from [this commit](https://gitlab.com/git-mirrors/grub/-/commit/93a786a00163e50c29f0394df198518617e1c9a5/). Or apparently you might be able to sign the font yourself but I haven't been able to figure out how to do that. 

See this thread: https://lists.gnu.org/archive/html/grub-devel/2022-11/msg00168.html
