### ISSUE TITLE
Ubuntu not running properly+package causing to failure configured like my laptop (a Linux Mint machine with no problems))

### ISSUE THREAD

**Issue by SallyTheUnknownMan** [AdisonCavani/distro-grub-themes#29]
-Describe the bug
The bug is this one: the grub cannot find hwatch and has resolution problems for 4:3 scailing with the resolution of 1280x1024 which causes grub to crash making me to manually select my boot entry

-Expected behavior
What i was expecting was to have it to run without unfixable issues at some lines with small code issues

-Screenshots:
I can't do any screenshot since it was in grub

-Desktop:
OS: Ubuntu 20.04.1 Focal Fossa
Resolution: 1280x1024

-Additional context:
I just hope that this issue will be fixed because out there are still people using square-type monitors on their pcs

**Comment by AdisonCavani** [comment]
This is caused by a bug  in Ubuntu Grub configuration.
It has been reported [here](https://bugs.launchpad.net/ubuntu/+source/grub2-signed/+bug/18405600).
[Currently it's waiting for merge](https://code.launchpad.net/~mfo/grub/+git/grub/+merge/407470)

Fix:
- Remove ``Countdown label`` in theme.txt
or:
- Edit ``/etc/default/grub`` and uncomment: ``GRUB_GFXPAYLOAD_LINUX=keep``. Save file and run ``sudo update-grub``

**Comment by SallyTheUnknownMan** [comment]
Hey @AdisonCavani, thanks for the reply, before i've seen this i changed my main rig's Ubuntu to Linux Mint. But thanks for the reply and helping people with the issues :)

Regards,
Sally Fisherman
