### ISSUE TITLE
Fonts?

### ISSUE THREAD

**Issue by Huso112** [AdisonCavani/distro-grub-themes#3]
This theme is awesome! But i want to chage the fonts. How can i dot it?

**Comment by AdisonCavani** [comment]
In order to customize font you need to generate a font in **.pf2** format. Ofc you need a .ttf font first and then you use this command:
```
grub-mkfont [OPTION...] [OPTIONS] FONT_FILES
```
Details on [Ubuntu manual page](https://manpages.ubuntu.com/manpages/trusty/man1/grub-mkfont.1.html)

You need to specify a font size and output. Then you change font name in ```theme.txt``` and that's all.
