### ISSUE TITLE
4k Support and Question

### ISSUE THREAD

**Issue by ProfessorManhattan** [AdisonCavani/distro-grub-themes#55]
Hey, it would be great to have 4k support but I have never been able to get GRUB to work with 4k. Don't you have to load proprietary graphics drivers to show GRUB in 4k? I would love to get this working... only macOS has a pleasant boot experience. I honestly can't believe we live in 2022 and we haven't even figured out how to make the FIRST thing we see when we boot our computers pretty. macOS did it.

Also, can we make the GRUB background change based on which OS is selected or do we have to choose a specific background? I'm just wondering why all the GRUB theme developers have custom backgrounds for each type of distro when the background probably makes more sense to be something that would make sense to the user regardless of which menu item is currently selected.

**Comment by AdisonCavani** [comment]
Have you tried to set ``GRUB_GFXMODE=640x480`` to you desired resolution?
I'm pretty sure it should work. 
The problem might be a font size. The font might be too small in this resolution. 

I might create a 2k & 4k themes in the future, but currently I'm not able to test it, since I have 1080p monitor. 

Grub has it own limitations. For example it doesn't support font anti-aliasing. It's very limited and it doesn't support chaning background based on selected entry.

You can try out some Grub alternatives. rEFInd might look a bit better.
