### ISSUE TITLE
Add new OEM vendors

### ISSUE THREAD

**Issue by Tuxman2** [AdisonCavani/distro-grub-themes#99]
Hello,

can you add new OEM vendors ?

- Medion
- Style Note.

Thanks.

**Comment by Silexium** [comment]
I would also like to suggest new themes, specifically for Linux Lite & Vanilla OS.

**Comment by joe733** [comment]
Hi @Tuxman2, can you convert this issue into a todo list, like so? (So that newer request to add vendors be reference here, instead of creating new issues for each vendor)

- [ ] [Medion](https://www.medion.com/us/products/laptops.php)
- [ ] [Clevo](https://www.clevo.com.tw/)
- [ ] [Clevo Computers](https://clevo-computer.com/en/)
- [ ] [Mi](https://www.mi.com/in/smart-office)


Also @AdisonCavani, if you can pin this issue, it would help. We can do the same for other distributions as well.

**Comment by AFCMS** [comment]
Could ASUS ROG and TUF brands be added too?

**Comment by joe733** [comment]
Asus as an OEM vendor already exists. https://k1ng.dev/distro-grub-themes/preview

**Comment by AFCMS** [comment]
> Asus as an OEM vendor already exists. https://k1ng.dev/distro-grub-themes/preview

I know.

**Comment by AdisonCavani** [comment]
@Tuxman2 I decided not to add Style Note, because:
- it's a "no-name" manufacturer
- it's not enough popular
- there is no good logo

There is a [`templates branch`](https://github.com/AdisonCavani/distro-grub-themes/tree/templates) which contains `.psd` templates.
You can make this theme yourself for personal use.
Use GIMP/ photoshop / [photopea.com](https://www.photopea.com)
